const fs=require('fs'),path=require('path'),vm=require('vm');
const base=path.resolve(process.argv[2]||path.join(__dirname,'..','..'));
function csv(file){const text=fs.readFileSync(path.join(base,'lionlink-operations-source/data',file),'utf8').replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if(ch==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=ch;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}const header=rows.shift();return rows.map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]||''])));}
const routes=csv('routes.csv'),stops=Object.fromEntries(csv('stops.csv').map(s=>[s.stop_id,s])),routeStops=csv('route_stops.csv'),trips=csv('trips.csv'),calls=csv('stop_calls.csv');
const output=path.join(__dirname,'dist','replay-data');fs.mkdirSync(output,{recursive:true});
const data={routes:{},dates:{},default:{date:'2026-10-07',services:['159','132'],start:21600,end:43200}};
for(const r of routes){data.routes[r.route_id]={service:r.service_no,direction:r.direction,name:r.service_name,loop:r.loop_route==='true',stops:routeStops.filter(s=>s.route_id===r.route_id).sort((a,b)=>+a.stop_order-+b.stop_order).map(s=>({id:s.stop_id,name:stops[s.stop_id].description,lat:+stops[s.stop_id].latitude,lon:+stops[s.stop_id].longitude,order:+s.stop_order,final:+s.stop_order===+r.stop_count}))};}
const seconds=timestamp=>{const t=timestamp.slice(11,19).split(':').map(Number);return t[0]*3600+t[1]*60+t[2];};
const tripMap=new Map();
for(const t of trips){data.dates[t.service_date]??={};data.dates[t.service_date][t.route_id]??={trips:[],queues:{}};const trip={id:t.trip_id,vehicle:t.actual_vehicle_id,calls:[]};data.dates[t.service_date][t.route_id].trips.push(trip);tripMap.set(t.trip_id,trip);}
for(const c of calls){const route=data.dates[c.service_date][c.route_id],order=+c.stop_order;tripMap.get(c.trip_id).calls.push([seconds(c.actual_arrival_at),seconds(c.actual_departure_at),order]);if(order===data.routes[c.route_id].stops.length)continue;route.queues[order]??=[];if(seconds(c.boarding_cutoff_at)<=43200)route.queues[order].push([seconds(c.boarding_cutoff_at),+c.queue_after_people,c.trip_id]);}
for(const dated of Object.values(data.dates))for(const route of Object.values(dated)){for(const t of route.trips)t.calls.sort((a,b)=>a[2]-b[2]);for(const q of Object.values(route.queues))q.sort((a,b)=>a[0]-b[0]||a[2].localeCompare(b[2]));}
fs.writeFileSync(path.join(output,'routes.js'),'window.REPLAY_ROUTES='+JSON.stringify(data.routes)+';');
for(const [date,dated] of Object.entries(data.dates))fs.writeFileSync(path.join(output,date+'.js'),'window.REPLAY_DATE='+JSON.stringify({date,routes:dated})+';');
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'dist/data.js'),'utf8'),ctx);const services=Object.values(ctx.window.PLANNER_DATA.services[data.default.date]).filter(s=>[s.delays.some(d=>d.minutes>=5),s.queue>=30,s.held.length>0].filter(Boolean).length>=2).map(s=>s.service);data.default.services=services;
const assetOut=path.join(base,'outputs','critical-service-replay');fs.mkdirSync(assetOut,{recursive:true});fs.writeFileSync(path.join(assetOut,'replay-data.json'),JSON.stringify(data));
console.log(JSON.stringify({dates:Object.keys(data.dates).length,routes:routes.length,trips:trips.length,critical:services,assetInput:path.join(assetOut,'replay-data.json')}));
