(() => {
'use strict';
const data=window.LIONLINK_PLANNING_DATA;
const stopOverlayData=window.LIONLINK_STOP_OVERLAY_DATA;
const $=id=>document.getElementById(id);
const scenarios={
 new:{name:'Plan a new route',title:'Test a new service',kicker:'NEW ROUTE · DECISION FLOW',steps:['Find the gap','Size demand','Check resources','Pilot & review'],panel:'Shape the service',sub:'Set the route, planning window and passenger assumptions.',checks:['Identify underserved destinations','Estimate passengers by stop and time','Set stops, cycle time and service frequency','Check bus and driver requirements','Pilot with ridership and waiting-time measures'],metrics:['Hourly demand','Buses needed','Drivers needed']},
 existing:{name:'Optimise an existing route',title:'Balance service across routes',kicker:'EXISTING ROUTE · DECISION FLOW',steps:['Check coverage','Compare capacity','Move resources','Trial & monitor'],panel:'Find a better balance',sub:'Reduce crowding on the busy service without losing coverage.',checks:['Test if donor frequency can reduce safely','Check remaining queues and passenger load','Locate spare or transferable capacity','Adjust dispatch spacing if bunching is the cause','Monitor both donor and recipient routes'],metrics:['Busy route demand','Donor route demand','Buses shifted']},
 maintenance:{name:'Bus in maintenance',title:'Protect service during downtime',kicker:'MAINTENANCE · DECISION FLOW',steps:['Map affected trips','Find replacement','Check donor route','Approve & restore'],panel:'Set the disruption window',sub:'Check a compatible released bus and driver before reducing service.',checks:['Identify downtime and affected departures','Check compatible bus and qualified crew','Check donor-route coverage before reassignment','Reduce frequency only within service limits','Monitor plan and restore after release'],metrics:['Affected demand','Buses to replace','Crew to assign']},
 connection:{name:'Missing connection',title:'Improve the onward journey',kicker:'ONWARD CONNECTION · DECISION FLOW',steps:['Measure gap','Diagnose cause','Compare options','Pilot & monitor'],panel:'Specify the connection gap',sub:'Compare timetable alignment, feeder service and access changes.',checks:['Measure onward destinations and demand','Check whether a service exists but timing misses','Compare extension, reroute or feeder options','Compare door-to-door time and operating impact','Track transfers, journey time and taxi dependence'],metrics:['Connection demand','Gap to bridge','Added cycle time']}
};
const state={scenario:'new',route:'B235_1',date:'2026-10-05',hours:4,peak:1.35,capacity:85,headway:12,cycle:72,baseline:12,donor:'B238_1',maintenanceHours:2,connectionDelay:12,walkAccess:1,selected:0,decision:'DRAFT PLAN',timelineStep:0,timelinePlaying:false,timelineFrame:0,timelineLast:0,toastTimer:null};
const round=(n,d=0)=>Number(n).toFixed(d), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const routes=data.routes.filter(r=>String(r.service_no)!=='');
const routeById=Object.fromEntries(routes.map(r=>[r.route_id,r]));
const serviceRoutes=[...new Map(routes.map(r=>[r.service_no,r])).values()];
let latestDecisionVisuals=null;
const sceneRouteOptions=routes.filter(r=>window.LIONLINK_ROUTE_3D_DATA?.routes?.[r.route_id]);
let sceneRouteIds=['B235_1','B238_1'].filter(id=>sceneRouteOptions.some(r=>r.route_id===id));
const safe=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function routeLabel(r){return `Service ${r.service_no} · ${r.direction===1?'outbound':'inbound'} · ${r.origin_name}`}
function routeSelect(id,value,routeList=routes){return `<select id="${id}">${routeList.map(r=>`<option value="${safe(r.route_id)}" ${r.route_id===value?'selected':''}>${safe(routeLabel(r))}</option>`).join('')}</select>`}
function renderSceneRoutePicker(){const host=$('scene-route-picker');if(!host)return;host.innerHTML=sceneRouteOptions.map(r=>`<button class="scene-route-chip ${sceneRouteIds.includes(r.route_id)?'selected':''}" type="button" data-scene-route="${safe(r.route_id)}" aria-pressed="${sceneRouteIds.includes(r.route_id)}">${safe(r.service_no)} · ${r.direction===1?'out':'in'}</button>`).join('');host.querySelectorAll('[data-scene-route]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.sceneRoute;if(sceneRouteIds.includes(id)){if(sceneRouteIds.length===1)return;sceneRouteIds=sceneRouteIds.filter(routeId=>routeId!==id)}else sceneRouteIds=[...sceneRouteIds,id];renderSceneRoutePicker();if(window.LionLink3D)window.LionLink3D.setRoutes(sceneRouteIds)}))}
function numField(label,id,value,min,max,step=1,unit='',full=false){return `<div class="field ${full?'full':''}"><label for="${id}">${label}</label><input id="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${value}">${unit?`<span class="range-readout">${unit}</span>`:''}</div>`}
function rangeField(label,id,value,min,max,step,unit){return `<div class="field full"><label for="${id}">${label}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><span class="range-readout"><span>${min} ${unit}</span><span class="range-value" data-range="${id}">${value} ${unit}</span><span>${max} ${unit}</span></span></div>`}
function fields(){const s=state.scenario;let html='';
 if(s==='new')html=`<div class="field full"><label for="route">Reference route / demand profile</label>${routeSelect('route',state.route)}</div><div class="field"><label for="date">Training date</label><select id="date">${Object.keys(data.resources).map(d=>`<option ${d===state.date?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label for="hours">Planning window</label><select id="hours"><option value="3" ${state.hours===3?'selected':''}>3-hour peak</option><option value="4" ${state.hours===4?'selected':''}>4-hour morning</option><option value="5" ${state.hours===5?'selected':''}>5-hour window</option></select></div>${rangeField('Demand uplift assumption','peak',state.peak,.75,2.25,.05,'×')}${numField('Usable bus capacity','capacity',state.capacity,40,150,1,'passengers')}${numField('Proposed departure interval','headway',state.headway,5,40,1,'minutes')}${numField('Round-trip + recovery','cycle',state.cycle,20,180,5,'minutes')}`;
 else if(s==='existing')html=`<div class="field full"><label for="route">Capacity receiving route</label>${routeSelect('route',state.route)}</div><div class="field full"><label for="donor">Potential donor route</label>${routeSelect('donor',state.donor,routes.filter(r=>r.service_no!==routeById[state.route]?.service_no))}</div><div class="field"><label for="date">Training date</label><select id="date">${Object.keys(data.resources).map(d=>`<option ${d===state.date?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label for="baseline">Donor interval now</label><input id="baseline" type="number" min="5" max="40" value="${state.baseline}"><span class="range-readout">minutes</span></div>${rangeField('Potential frequency reduction','peak',state.peak,.75,2.25,.05,'×')}${numField('Usable bus capacity','capacity',state.capacity,40,150,1,'passengers')}${numField('Added departures to receiving route','headway',state.headway,1,8,1,'buses / peak')}`;
 else if(s==='maintenance')html=`<div class="field full"><label for="route">Affected route</label>${routeSelect('route',state.route)}</div><div class="field"><label for="date">Training date</label><select id="date">${Object.keys(data.resources).map(d=>`<option ${d===state.date?'selected':''}>${d}</option>`).join('')}</select></div>${numField('Expected downtime','maintenanceHours',state.maintenanceHours,1,8,1,'hours')}<div class="field full"><label for="donor">Potential donor route</label>${routeSelect('donor',state.donor,routes.filter(r=>r.service_no!==routeById[state.route]?.service_no))}</div>${rangeField('Capacity pressure on affected route','peak',state.peak,.75,2.25,.05,'×')}${numField('Usable bus capacity','capacity',state.capacity,40,150,1,'passengers')}${numField('Round-trip + recovery','cycle',state.cycle,20,180,5,'minutes')}`;
 else html=`<div class="field full"><label for="route">Connection route</label>${routeSelect('route',state.route)}</div><div class="field"><label for="date">Training date</label><select id="date">${Object.keys(data.resources).map(d=>`<option ${d===state.date?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label for="walkAccess">Access improvement</label><select id="walkAccess"><option value="0">No access change</option><option value="1" ${state.walkAccess===1?'selected':''}>Walking / stop access</option><option value="2" ${state.walkAccess===2?'selected':''}>Accessible boarding</option></select></div>${numField('Connection delay / missed window','connectionDelay',state.connectionDelay,3,60,1,'minutes')}${rangeField('Estimated onward demand uplift','peak',state.peak,.75,2.25,.05,'×')}${numField('Usable bus capacity','capacity',state.capacity,40,150,1,'passengers')}${numField('Added cycle time','cycle',state.cycle,20,180,5,'minutes')}`;
 $('form-fields').innerHTML=html;
 $('form-fields').querySelectorAll('input,select').forEach(el=>{
  const update=()=>{if(el.id==='route'){state.route=el.value;const donor=$('donor');if(donor&&routeById[donor.value]?.service_no===routeById[state.route]?.service_no)state.donor=routes.find(r=>r.service_no!==routeById[state.route]?.service_no).route_id;}else if(el.id==='donor')state.donor=el.value;else if(el.id==='date')state.date=el.value;else if(el.type==='number')state[el.id]=Number(el.value);else if(el.type==='range'){state[el.id]=Number(el.value);const read=document.querySelector(`[data-range="${el.id}"]`);if(read)read.textContent=Number(el.value).toFixed(2)+' ×'}render();if(window.LionLink3D){window.LionLink3D.setRoute(state.route);window.LionLink3D.setDonor(state.donor);window.LionLink3D.setDate(state.date);sceneRouteIds=window.LionLink3D.getRoutes();renderSceneRoutePicker()}};
  if(el.type==='range'){el.addEventListener('input',()=>{const read=document.querySelector(`[data-range="${el.id}"]`);if(read)read.textContent=Number(el.value).toFixed(2)+' ×'});el.addEventListener('change',update)}else el.addEventListener('change',update);
 });
}
function observedDemand(routeId,date,hours){const batches=data.arrivals[`${date}|${routeId}`]||[];const limit=6+hours*60;const recent=batches.filter(([t])=>{const [h,m]=t.split(':').map(Number);return h*60+m>=360&&h*60+m<360+limit;});const total=recent.reduce((a,b)=>a+b[1],0);return {total,hourly:total/hours,batches:recent.length,all:batches.length}}
function queueSignal(routeId,date){const q=data.queues[`${date}|${routeId}`];if(!q)return {total:0,remaining:0,windows:0};return q}
function getModel(){const r=routeById[state.route]||routes[0],d=routeById[state.donor]||routes.find(x=>x.service_no!==r.service_no),h=state.hours||4;const obs=observedDemand(r.route_id,state.date,h);const observed=obs.hourly;const q=queueSignal(r.route_id,state.date);const demand=observed*state.peak;const cycle=state.cycle||72;const perBusPerHour=state.capacity*60/state.headway;const buses=Math.ceil(cycle/state.headway);const baseResource=data.resources[state.date]||{released_buses:0,crew_duties:0};let cap=perBusPerHour;let metric1=demand,metric2=buses,metric3=Math.ceil(cycle/state.headway);let opts=[];let insight='';
 if(state.scenario==='new'){
  const shortfall=Math.max(0,demand-cap);opts=[{title:'Pilot at peak frequency',desc:'Run a short, measured pilot on the proposed corridor and review boarding, waits and cost per passenger.',buses,interval:state.headway,coverage:'Full proposed window',fit:'Demand-led',score:shortfall?1:0},{title:'Start with a shorter window',desc:'Focus departures on the highest-demand hours; extend only if the pilot shows unmet demand.',buses:Math.ceil(cycle/state.headway),interval:state.headway,coverage:`${Math.max(1,h-1)} peak hours`,fit:'Lower exposure',score:1},{title:'Use a higher-capacity bus',desc:'Keep the interval and route design, then test whether a larger vehicle covers the peak with fewer departures.',buses:Math.ceil(cycle/state.headway),interval:state.headway,coverage:'Full proposed window',fit:'Capacity option',score:2}];insight=shortfall?`At the current interval, illustrative capacity is <b>${round(cap)} passengers/hour</b> versus <b>${round(demand)} forecast</b>. A shortfall of about ${round(shortfall)} passengers/hour needs a service or vehicle-capacity adjustment.`:`The illustrative service capacity is about <b>${round(cap)} passengers/hour</b>, above the scenario demand estimate of <b>${round(demand)}</b>. Confirm the underserved-destination evidence before adding service.`;
 }else if(state.scenario==='existing'){
  const donorObs=observedDemand(d.route_id,state.date,h),donorD=donorObs.hourly*state.peak;const shift=Math.max(1,Math.min(4,Math.ceil(state.headway||2)));metric1=demand;metric2=donorD;metric3=shift;cap=perBusPerHour;opts=[{title:'Shift one bus from donor route',desc:`Move a bus and qualified driver from Service ${d.service_no} after checking its queue and coverage.`,buses:1,interval:Math.max(5,Math.round((state.baseline||12)*1.2)),coverage:'Targeted peak boost',fit:donorD<cap*.7?'Donor has headroom':'Donor risk to check',score:donorD<cap*.7?0:2},{title:'Shift two buses for a stronger boost',desc:'Add two peak departures; explicitly monitor the donor route for a queue increase.',buses:2,interval:Math.max(5,Math.round((state.baseline||12)*.8)),coverage:'Higher receiving capacity',fit:'More donor impact',score:1},{title:'Adjust spacing before adding capacity',desc:'If bunching drives waits, retime departures and recovery before moving buses.',buses:0,interval:state.baseline||12,coverage:'No donor resource moved',fit:'Dispatch intervention',score:1}];insight=`Receiving route signal: <b>${round(demand)} passengers/hour</b>. Donor route signal: <b>${round(donorD)}</b>. Route-wide availability cannot be inferred from morning fleet totals; verify live queue, trips and crew before transfer.`;
 }else if(state.scenario==='maintenance'){
  const trips=Math.max(1,Math.round(state.maintenanceHours*60/state.headway));metric1=demand;metric2=1;metric3=1;opts=[{title:'Use a released compatible spare',desc:'Assign a released bus and qualified driver; verify location, time window and existing duties.',buses:1,interval:state.headway,coverage:`Protect about ${trips} departures`,fit:'Check dated availability',score:0},{title:'Borrow from a quieter route',desc:`Check Service ${d.service_no} donor route and qualified crew, then monitor its remaining capacity.`,buses:1,interval:state.headway,coverage:`Protect about ${trips} departures`,fit:'Donor impact review',score:1},{title:'Temporarily reduce frequency',desc:'Publish revised departure times only if remaining capacity and wait limits stay acceptable.',buses:0,interval:Math.ceil(state.headway*1.5),coverage:'Reduced departures',fit:'Passenger impact',score:2}];insight=`A ${state.maintenanceHours}-hour downtime window intersects an estimated <b>${trips} departures</b> at a ${state.headway}-minute interval. Snapshot shows ${baseResource.released_buses} released buses for the whole date; that is not a spare count and does not prove compatibility.`;
 }else{
  const gap=state.connectionDelay,extra=Math.ceil(cycle/state.headway);metric1=demand;metric2=gap;metric3=extra;opts=[{title:'Align the connecting departure',desc:'Retiming an existing service may close the gap without adding a route; validate last-service and downstream impacts.',buses:0,interval:state.headway,coverage:`Target ${gap}-minute connection gap`,fit:'Lowest resource change',score:0},{title:'Add a feeder connection',desc:'Pilot a short feeder if timing alone cannot close the gap; check demand and operating cycle.',buses:1,interval:state.headway,coverage:'New transfer option',fit:'Bus + crew required',score:1},{title:'Improve stop access',desc:'Assess walking route, accessibility and stop placement where the vehicle service already exists.',buses:0,interval:0,coverage:'Door-to-door access',fit:state.walkAccess?'Access option selected':'Access check needed',score:state.walkAccess?0:2}];insight=`The records include no observed transfer outcomes. Treat the <b>${gap}-minute connection gap</b> and demand uplift as client-confirmed scenario inputs; geography alone cannot establish an accessible connection.`;
 }
 return {r,d,obs,q,demand,cap,buses,metric1,metric2,metric3,opts,insight,resource:baseResource,h};
}
function renderSteps(){const steps=scenarios[state.scenario].steps;const progress=Math.min(state.selected+1,steps.length-1);$('flow-steps').innerHTML=steps.map((x,i)=>`<div class="flow-node"><div class="flow-step ${i===progress?'current':i<progress?'done':''}"><span class="step-number">${i<progress?'✓':i+1}</span>${safe(x)}</div>${i<steps.length-1?'<div class="flow-line"></div>':''}</div>`).join('')}
function drawChart(m){const d=m.demand,c=m.cap,peak=Math.max(d,c,1)*1.15;const labels=['06–07','07–08','08–09','09–10','10–11'];$('chart').innerHTML=`<span class="chart-y" style="top:6px">${round(peak)}</span><span class="chart-y" style="top:42px">${round(peak*.65)}</span><span class="chart-y" style="bottom:20px">0</span>`+labels.map((l,i)=>{const mod=[.68,.9,1.15,1.07,.77][i],dh=clamp(d*mod/peak*88,3,88),ch=clamp(c/peak*88,3,88);return `<div class="bar-group"><i class="bar demand" style="height:${dh}%" title="Demand: ${round(d*mod)}"></i><i class="bar capacity" style="height:${ch}%" title="Capacity: ${round(c)}"></i><span class="bar-label">${l}</span></div>`}).join('');$('chart').setAttribute('aria-label',`Illustrative forecast demand ${round(d)} passengers per hour and usable capacity ${round(c)} passengers per hour`)}
function metric(label,value,note){return `<div class="metric"><label>${label}</label><strong>${value}</strong><small>${note}</small></div>`}
function renderOptions(m){$('options').innerHTML=m.opts.map((o,i)=>`<article class="option-card ${i===state.selected?'selected':''} ${i===0?'recommended':''}" data-option="${i}" tabindex="0" role="button" aria-pressed="${i===state.selected}"><h4>${safe(o.title)}</h4><p>${safe(o.desc)}</p><div class="option-stats"><span><b>${o.buses}</b> bus${o.buses===1?'':'es'}</span><span><b>${o.interval||'—'}</b> min interval</span><span>${safe(o.coverage)}</span></div><div class="fit-label">Resource fit · ${safe(o.fit)}</div></article>`).join('');document.querySelectorAll('.option-card').forEach(el=>{const choose=()=>{state.selected=Number(el.dataset.option);state.decision='DRAFT PLAN';render()};el.addEventListener('click',choose);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}})})}
function updateAllocationSimulation(m){const option=m.opts[state.selected]||m.opts[0];const wasSimulating=$('allocation-sim-view').querySelector('.sim-bus-token');const savedLeft=wasSimulating?wasSimulating.style.left:'';const steps=Array.from({length:6},(_,i)=>{
 const phase=['06:30','07:00','07:30','08:00','08:30','09:00'][i];
 const wave=[.74,.94,1.12,1.2,1.04,.82][i];
 let recipient=m.demand*wave,donor=m.metric2*wave,recipientCapacity=m.cap,donorCapacity=m.cap;
 if(state.scenario==='existing'){
  const shift=Number(option.buses)||0;
  recipientCapacity+=shift*state.capacity*60/(option.interval||state.headway);
  donorCapacity=Math.max(0,donorCapacity-shift*state.capacity*60/(state.baseline||12));
 }else if(state.scenario==='maintenance'){
  recipientCapacity=Math.max(0,recipientCapacity-(option.buses?0:state.capacity*60/state.headway));
  if(option.title.includes('released'))recipientCapacity+=state.capacity*60/state.headway;
 }else if(state.scenario==='new'||state.scenario==='connection') recipientCapacity=state.capacity*60/(option.interval||state.headway);
 return {phase,recipient,donor,recipientCapacity,donorCapacity};
 });
 const title=state.scenario==='existing'?'Receiving route':state.scenario==='maintenance'?'Affected route':state.scenario==='connection'?'Connection route':'Proposed service';
 const donorName=state.scenario==='existing'||state.scenario==='maintenance'?`Service ${m.d.service_no}`:'Current / reference service';
 const max=Math.max(1,...steps.flatMap(x=>[x.recipient,x.donor,x.recipientCapacity,x.donorCapacity]));
 const bars=(value,capacity,label)=>`<div class="sim-bar-pair"><span>${label}</span><div class="sim-bars"><i class="sim-bar demand-bar" style="width:${clamp(value/max*100,1,100)}%"></i><i class="sim-bar capacity-bar" style="width:${clamp(capacity/max*100,1,100)}%"></i></div><b>${round(value)} / ${round(capacity)}</b></div>`;
 $('allocation-sim-caption').textContent=`${option.title} · ${state.date} · selected option updates the replay`;
 $('allocation-sim-view').innerHTML=`<div class="sim-routes"><div class="sim-route-card"><div class="sim-route-head"><b>${safe(title)}</b><small>Service ${safe(m.r.service_no)} · ${safe(routeById[state.route]?.direction===1?'outbound':'inbound')}</small></div><div class="sim-road"><span class="sim-stop-dot"></span><span class="sim-road-line"></span><span class="sim-stop-dot"></span><span class="sim-bus-token" aria-hidden="true">▰</span></div>${steps.map(x=>bars(x.recipient,x.recipientCapacity,x.phase)).join('')}</div><div class="sim-transfer"><span class="sim-transfer-count">${option.buses?`${option.buses} bus${option.buses===1?'':'es'} →`:'↔'}</span><span class="sim-transfer-line"></span><small>${safe(option.coverage)}</small></div><div class="sim-route-card donor-card"><div class="sim-route-head"><b>${safe(donorName)}</b><small>${state.scenario==='existing'||state.scenario==='maintenance'?'Donor impact check':'Baseline comparison'}</small></div><div class="sim-road"><span class="sim-stop-dot"></span><span class="sim-road-line"></span><span class="sim-stop-dot"></span><span class="sim-bus-token" aria-hidden="true">▰</span></div>${steps.map(x=>bars(x.donor,x.donorCapacity,x.phase)).join('')}</div></div><div class="sim-legend"><span><i class="sim-legend-demand"></i>Passenger demand</span><span><i class="sim-legend-capacity"></i>Available capacity</span></div>`;
 $('allocation-sim-view').querySelectorAll('.sim-bus-token').forEach(bus=>{bus.style.left=savedLeft||'8%';bus.classList.toggle('moving',allocationPlaying)});
 const recipientGap=steps.reduce((sum,x)=>sum+Math.max(0,x.recipient-x.recipientCapacity),0)/steps.length;
 const donorGap=steps.reduce((sum,x)=>sum+Math.max(0,x.donor-x.donorCapacity),0)/steps.length;
 $('allocation-sim-metrics').innerHTML=`<div><small>Selected plan</small><b>${safe(option.title)}</b></div><div><small>Recipient uncovered demand · avg</small><b>${round(recipientGap)} passengers/hour</b></div><div><small>${safe(donorName)} uncovered demand · avg</small><b>${round(donorGap)} passengers/hour</b></div><div><small>Scenario resources</small><b>${option.buses} bus${option.buses===1?'':'es'} · crew check required</b></div>`;
 latestDecisionVisuals={model:m,steps,option};renderDecisionVisuals(m,steps,option);
 if(window.LionLink3D){window.LionLink3D.setAllocation(option.buses,state.headway);window.LionLink3D.setProgress(state.timelineStep/Math.max(1,steps.length-1))}
}
function renderDecisionVisuals(m,simSteps,option){const times=simSteps.map(x=>x.phase);state.timelineStep=clamp(state.timelineStep,0,simSteps.length-1);const step=simSteps[state.timelineStep]||simSteps[0];const selectedRoute=routeById[state.route],donor=routeById[state.donor]||routes.find(r=>r.service_no!==selectedRoute.service_no);const receivingCapacity=step.recipientCapacity,donorCapacity=step.donorCapacity;
 const routeNode=(name,demand,capacity,role)=>`<div class="ripple-node ${role}"><span class="ripple-pulse"></span><b>${safe(name)}</b><small>${round(demand)} demand · ${round(capacity)} capacity</small><div class="ripple-pressure"><i style="width:${clamp(demand/Math.max(1,capacity)*100,2,100)}%"></i></div></div>`;
 $('ripple-view').innerHTML=`${routeNode(`Service ${selectedRoute.service_no}`,step.recipient,receivingCapacity,'recipient-node')}<div class="ripple-link"><span class="ripple-bus">▰</span><i></i><small>${option.buses?`${option.buses} bus${option.buses===1?'':'es'} proposed`:'No bus transfer'}</small></div>${routeNode(`Service ${donor.service_no}`,step.donor,donorCapacity,'donor-node')}`;
 $('ripple-copy').textContent=`At ${step.phase}, recipient capacity is ${round(receivingCapacity)} passengers/hour. Donor capacity after the selected option is ${round(donorCapacity)} passengers/hour. These are scenario estimates; confirm actual duties, fleet availability and route coverage.`;
 const range=$('timeline-range');range.value=String(state.timelineStep);$('timeline-time-label').textContent=step.phase;$('replay-time').textContent=step.phase;
 const maxDemand=Math.max(1,...simSteps.map(x=>x.recipient));$('timeline-view').innerHTML=`<div class="timeline-chart">${simSteps.map((x,i)=>`<button class="timeline-point ${i===state.timelineStep?'active':''}" data-step="${i}" type="button" aria-label="Select ${x.phase}"><span class="timeline-demand" style="height:${clamp(x.recipient/maxDemand*84,5,84)}%"></span><span class="timeline-capacity" style="height:${clamp(x.recipientCapacity/maxDemand*84,5,84)}%"></span><small>${x.phase}</small></button>`).join('')}</div><div class="timeline-legend"><span><i class="demand-swatch"></i>Passenger demand</span><span><i class="capacity-swatch"></i>Available capacity</span></div>`;
 $('timeline-pressure-label').textContent=`${round(step.recipient)} demand / ${round(step.recipientCapacity)} capacity`;
 const queueAtTime=queueSignal(selectedRoute.route_id,state.date);
 $('timeline-detail').textContent=`Sample date ${state.date} · route-level queue snapshot: ${queueAtTime.remaining} people remaining across ${queueAtTime.windows} observed windows. The time-varying demand profile is a replay scaled from the supplied arrival sample; queue-by-stop time series are not available.`;
 const receivingGap=Math.max(0,step.recipient-receivingCapacity),donorGap=Math.max(0,step.donor-donorCapacity),receivingSpare=Math.max(0,receivingCapacity-step.recipient),donorSpare=Math.max(0,donorCapacity-step.donor);
 $('balance-view').innerHTML=`<div class="balance-side benefit-side"><b>Recipient benefit</b><div><span>Uncovered demand</span><strong>${round(receivingGap)}</strong></div><div><span>Spare capacity</span><strong>${round(receivingSpare)}</strong></div><small>Passengers/hour at ${step.phase}</small></div><div class="balance-center"><span class="balance-transfer">${option.buses} bus${option.buses===1?'':'es'}</span><i style="--tilt:${clamp((receivingGap-donorGap)/Math.max(1,Math.max(receivingGap,donorGap))*18,-18,18)}deg"></i><small>Crew qualification check</small></div><div class="balance-side risk-side"><b>Donor impact</b><div><span>Uncovered demand</span><strong>${round(donorGap)}</strong></div><div><span>Spare capacity</span><strong>${round(donorSpare)}</strong></div><small>Passengers/hour at ${step.phase}</small></div>`;
 $('replay-view').innerHTML=`<div class="replay-lane before-lane"><b>Before</b><small>Current planning baseline</small><div class="replay-road"><i class="replay-bus"></i></div><div class="replay-bars"><span>Demand</span><i><em style="width:${clamp(step.recipient/Math.max(1,step.recipient,step.recipientCapacity)*100,2,100)}%"></em></i><b>${round(step.recipient)}</b></div><div class="replay-bars"><span>Capacity</span><i><em style="width:${clamp(step.recipientCapacity/Math.max(1,step.recipient,step.recipientCapacity)*100,2,100)}%"></em></i><b>${round(step.recipientCapacity)}</b></div></div><div class="replay-lane after-lane"><b>After</b><small>${safe(option.title)}</small><div class="replay-road"><i class="replay-bus"></i><i class="replay-bus added-bus"></i></div><div class="replay-bars"><span>Demand</span><i><em style="width:${clamp(step.recipient/Math.max(1,step.recipient,receivingCapacity)*100,2,100)}%"></em></i><b>${round(step.recipient)}</b></div><div class="replay-bars"><span>Capacity</span><i><em style="width:${clamp(receivingCapacity/Math.max(1,step.recipient,receivingCapacity)*100,2,100)}%"></em></i><b>${round(receivingCapacity)}</b></div></div>`;
 const boardRows=((stopOverlayData?.byDate?.[state.date]?.[selectedRoute.route_id])||{});const stopData=Object.entries(boardRows).map(([order,row])=>({order:Number(order),...row})).sort((a,b)=>a.order-b.order);const maxBoard=Math.max(1,...stopData.map(x=>x.boardings));
 $('ribbon-total').textContent=`${stopData.reduce((n,x)=>n+x.boardings,0).toLocaleString()} boardings · ${state.date}`;
 $('crowding-ribbon').innerHTML=stopData.length?stopData.map((x,i)=>`<div class="crowd-stop ${i===state.timelineStep%Math.max(1,stopData.length)?'current':''}" title="Stop ${x.order} · ${x.stopId} · ${x.boardings} boardings"><span class="crowd-bar" style="height:${12+Math.sqrt(x.boardings/maxBoard)*46}px;opacity:${.45+x.boardings/maxBoard*.55}"></span><b>${x.order}</b><small>${x.boardings}</small></div>`).join(''):'<p class="empty-ribbon">No stop-call boardings for this route and date.</p>';
 $('ribbon-footnote').textContent=stopData.length?'Color and bar height show total boarding events by route stop on the selected service date. Queue-by-stop time series are not available in the sample.':'Choose a route/date with stop-call records to view boarding concentration.';
 $('timeline-view').querySelectorAll('.timeline-point').forEach(button=>button.addEventListener('click',()=>{state.timelineStep=Number(button.dataset.step);render()}));
}
function summary(m){const o=m.opts[state.selected]||m.opts[0],entries=[['Scenario',scenarios[state.scenario].name],['Route',`Service ${m.r.service_no} · ${m.r.direction===1?'outbound':'inbound'}`],['Selected option',o.title],['Demand signal',`${round(m.demand)} / hour`],['Resource ask',`${o.buses} bus${o.buses===1?'':'es'} · ${o.buses?'crew check':'no bus transfer'}`],['Service trade-off',o.coverage]];$('summary-list').innerHTML=entries.map(([k,v])=>`<div class="summary-row"><span>${safe(k)}</span><b>${safe(v)}</b></div>`).join('');$('approval-lede').textContent=state.scenario==='new'?'Review the passenger case, frequency and required resources before a pilot.':'Review passenger impacts and the donor / resource trade-off before approval.'}
function render(){const cfg=scenarios[state.scenario];$('workflow-label').textContent=cfg.kicker;$('scenario-title').textContent=cfg.title;$('panel-title').textContent=cfg.panel;$('panel-subtitle').textContent=cfg.sub;$('input-source').textContent='Synthetic sample + assumptions';$('chart-period').textContent=`${state.hours||4}-HOUR WINDOW · PER HOUR`;$('forecast-caption').textContent=`${routeById[state.route]?.service_name||'Selected route'} · ${state.date}`;document.querySelectorAll('.scenario-card').forEach(b=>b.classList.toggle('active',b.dataset.scenario===state.scenario));fields();renderSteps();const m=getModel();
 updateAllocationSimulation(m);
 const label=cfg.metrics;let mm;if(state.scenario==='new')mm=[metric(label[0],round(m.demand),`Observed ${round(m.obs.hourly)} × ${state.peak.toFixed(2)} uplift`),metric(label[1],m.buses,`${state.cycle} min cycle ÷ ${state.headway} min interval`),metric(label[2],m.buses,`One driver per active bus assumption`)];else if(state.scenario==='existing')mm=[metric(label[0],round(m.demand),`receiving route · / hour`),metric(label[1],round(m.metric2),`donor route · / hour`),metric(label[2],m.metric3,`candidate transfer · scenario`)];else if(state.scenario==='maintenance')mm=[metric(label[0],round(m.demand),`affected route · / hour`),metric(label[1],m.metric2,`${state.maintenanceHours}h downtime scenario`),metric(label[2],m.metric3,`qualified duty check needed`)];else mm=[metric(label[0],round(m.demand),`onward demand · scenario / hour`),metric(label[1],`${m.metric2} min`,`connection delay assumption`),metric(label[2],m.metric3,`${state.cycle} min cycle estimate`)];$('metrics').innerHTML=mm.join('');drawChart(m);$('insight').innerHTML=`<b>Planning signal.</b> ${m.insight}`;renderOptions(m);summary(m);$('flow-detail').innerHTML=`<h3>Workflow checklist · ${safe(cfg.name)}</h3><div class="workflow-checks">${cfg.checks.map((x,i)=>`<span class="workflow-check"><b>${i+1}</b>${safe(x)}</span>`).join('')}</div>`;$('review-status').textContent=state.decision;$('review-status').style.background=state.decision==='APPROVED'?'#e7f4ed':state.decision==='DRAFT SAVED'?'#eef2f4':'#fbf5e5';$('approve').innerHTML=state.decision==='APPROVED'?'Plan approved <span>✓</span>':'Approve this plan <span>→</span>';$('approve').disabled=state.decision==='APPROVED';}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
document.querySelectorAll('.scenario-card').forEach(btn=>btn.addEventListener('click',()=>{state.scenario=btn.dataset.scenario;state.selected=0;state.decision='DRAFT PLAN';render()}));
$('reset').addEventListener('click',()=>{state.selected=0;state.peak=1.35;state.headway=12;state.cycle=72;state.maintenanceHours=2;state.connectionDelay=12;state.decision='DRAFT PLAN';render();toast('Scenario inputs reset')});
$('approve').addEventListener('click',()=>{state.decision='APPROVED';render();toast('Plan marked approved for prototype review')});$('save-draft').addEventListener('click',()=>{state.decision='DRAFT SAVED';render();toast('Draft saved in this browser session')});
$('data-details').addEventListener('click',()=>$('scope-dialog').showModal());$('close-dialog').addEventListener('click',()=>$('scope-dialog').close());$('scope-dialog').addEventListener('click',e=>{if(e.target===$('scope-dialog'))$('scope-dialog').close()});
if(!data){document.body.innerHTML='<main style="padding:48px;font:16px sans-serif">Local planning snapshot is missing. Keep snapshot.js beside index.html.</main>';return}
let allocationAnimationFrame=0,allocationPlaying=true,allocationTick=0;
function animateAllocation(now){if(!allocationPlaying||document.hidden){allocationAnimationFrame=requestAnimationFrame(animateAllocation);return}if(!animateAllocation.last)animateAllocation.last=now;const delta=Math.min(now-animateAllocation.last,100);animateAllocation.last=now;allocationTick=(allocationTick+delta/2200)%6;const active=Math.floor(allocationTick);document.querySelectorAll('.sim-bus-token').forEach(bus=>{bus.style.left=`${8+(allocationTick%1)*76}%`;bus.classList.toggle('moving',allocationPlaying)});document.querySelectorAll('.sim-bar-pair').forEach((row,i)=>row.classList.toggle('sim-now',i%6===active));allocationAnimationFrame=requestAnimationFrame(animateAllocation)}
$('allocation-play-toggle').addEventListener('click',()=>{allocationPlaying=!allocationPlaying;$('allocation-play-toggle').textContent=allocationPlaying?'Ⅱ Pause simulation':'▶ Resume simulation';$('allocation-play-toggle').setAttribute('aria-pressed',String(allocationPlaying));if(allocationPlaying){animateAllocation.last=0;cancelAnimationFrame(allocationAnimationFrame);allocationAnimationFrame=requestAnimationFrame(animateAllocation)}});
let timelineAnimationFrame=0;function refreshLinkedTime(){if(!latestDecisionVisuals)return;renderDecisionVisuals(latestDecisionVisuals.model,latestDecisionVisuals.steps,latestDecisionVisuals.option);if(window.LionLink3D)window.LionLink3D.setProgress(state.timelineStep/5)}
function animateTimeline(now){if(state.timelinePlaying&&!document.hidden){if(!state.timelineLast)state.timelineLast=now;if(now-state.timelineLast>=1500){state.timelineStep=(state.timelineStep+1)%6;state.timelineLast=now;refreshLinkedTime()}}timelineAnimationFrame=requestAnimationFrame(animateTimeline)}
window.addEventListener('lionlink-route-time',event=>{state.timelineStep=Math.round(event.detail.progress*5);if(latestDecisionVisuals)renderDecisionVisuals(latestDecisionVisuals.model,latestDecisionVisuals.steps,latestDecisionVisuals.option)});
$('timeline-range').addEventListener('input',event=>{state.timelineStep=Number(event.target.value);state.timelineLast=performance.now();refreshLinkedTime()});
 $('timeline-play-toggle').textContent='▶ Play';$('timeline-play-toggle').setAttribute('aria-pressed','false');
 $('timeline-play-toggle').addEventListener('click',()=>{state.timelinePlaying=!state.timelinePlaying;$('timeline-play-toggle').textContent=state.timelinePlaying?'Ⅱ Pause':'▶ Play';$('timeline-play-toggle').setAttribute('aria-pressed',String(state.timelinePlaying));state.timelineLast=performance.now();if(window.LionLink3D)window.LionLink3D.setPlaying(!state.timelinePlaying)});
render();
renderSceneRoutePicker();
allocationAnimationFrame=requestAnimationFrame(animateAllocation);
timelineAnimationFrame=requestAnimationFrame(animateTimeline);
if(window.LionLink3D){window.LionLink3D.setRoute(state.route);window.LionLink3D.setDonor(state.donor);window.LionLink3D.setDate(state.date);window.LionLink3D.setRoutes(sceneRouteIds)}
})();
